export const PRODUCT_IMAGE_ASPECT_RATIO_WIDTH = 4;
export const PRODUCT_IMAGE_ASPECT_RATIO_HEIGHT = 5;

export const PRODUCT_IMAGE_ASPECT_CLASS = 'aspect-[4/5]';
export const PRODUCT_CARD_IMAGE_ASPECT_CLASS = 'aspect-[4/5]';

export const PRODUCT_IMAGE_UPLOAD_WIDTH = 576;
export const PRODUCT_IMAGE_UPLOAD_HEIGHT = 720;

export const PRODUCT_IMAGE_CROP_HINT = `تصویر قبل از آپلود با نسبت ${PRODUCT_IMAGE_ASPECT_RATIO_WIDTH}:${PRODUCT_IMAGE_ASPECT_RATIO_HEIGHT} و اندازه ${PRODUCT_IMAGE_UPLOAD_WIDTH}×${PRODUCT_IMAGE_UPLOAD_HEIGHT} برش داده می‌شود.`;

export const PRODUCT_IMAGE_GALLERY_CROP_HINT = `همه تصاویر گالری قبل از آپلود با نسبت ${PRODUCT_IMAGE_ASPECT_RATIO_WIDTH}:${PRODUCT_IMAGE_ASPECT_RATIO_HEIGHT} و اندازه ${PRODUCT_IMAGE_UPLOAD_WIDTH}×${PRODUCT_IMAGE_UPLOAD_HEIGHT} برش داده می‌شوند.`;
